[Writable]
  LogLevel = "INFO"

  [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = "5m"
    MaxRetryCount = 10

  # The Pipeline section allows the functions pipeline to be specified via configuration
  [Writable.Pipeline]
    # If True, the incoming data to the functions pipeline will be []byte, i.e not marshaled to an Event
    # This is useful when the incoming data isn't an EdgeX Event.
    UseTargetTypeOfByteArray = false

    # ExecutionOrder specifies which functions to run and the order to run them.
    # All functions listed must have an entry below in the Pipeline.Functions section
    ExecutionOrder = "FilterByDeviceName, TransformToXML, SetOutputData"

    # The Pipeline.Functions sections define the parameter configuration for each specific function.
    # These function names must match a function define in the configurable package of the SDK.
    # See the Built-In Transforms/Functions section of the SDK"s README for complete list.
    # Some functions do not require any parameters, but still must be listed.
    # Also, functions not specified in ExecutionOrder above can still be included which allows for easier
    # dynamic changes from Consul.
    [Writable.Pipeline.Functions.FilterByDeviceName]
      [Writable.Pipeline.Functions.FilterByDeviceName.Parameters]
        DeviceNames = "Random-Float-Device,Random-Integer-Device"
    [Writable.Pipeline.Functions.FilterByValueDescriptor]
      [Writable.Pipeline.Functions.FilterByValueDescriptor.Parameters]
        ValueDescriptors = "RandomValue_Int8, RandomValue_Int64"
    [Writable.Pipeline.Functions.TransformToXML]
    [Writable.Pipeline.Functions.TransformToJSON]
    [Writable.Pipeline.Functions.CompressWithGZIP]
    [Writable.Pipeline.Functions.CompressWithZLIB]
    [Writable.Pipeline.Functions.EncryptWithAES]
      [Writable.Pipeline.Functions.EncryptWithAES.Parameters]
        Key = "aquqweoruqwpeoruqwpoeruqwpoierupqoweiurpoqwiuerpqowieurqpowieurpoqiweuroipwqure"
        InitVector = "123456789012345678901234567890"
    [Writable.Pipeline.Functions.SetOutputData]
    [Writable.Pipeline.Functions.MarkAsPushed]
    [Writable.Pipeline.Functions.PushToCore]
      [Writable.Pipeline.Functions.PushToCore.Parameters]
        DeviceName = ""
        ReadingName = ""
    [Writable.Pipeline.Functions.HTTPPost]
      [Writable.Pipeline.Functions.HTTPPost.Parameters]
        url = "http://"
        mimeType = "" #OPTIONAL - default application/json
        persistOnError = "false"
    [Writable.Pipeline.Functions.HTTPPostJSON]
      [Writable.Pipeline.Functions.HTTPPostJSON.Parameters]
        url = "http://"
        persistOnError = "false"
    [Writable.Pipeline.Functions.HTTPPostXML]
      [Writable.Pipeline.Functions.HTTPPostXML.Parameters]
        url = "http://"
        persistOnError = "false"
    [Writable.Pipeline.Functions.MQTTSend]
      [Writable.Pipeline.Functions.MQTTSend.Parameters]
        qos="0"
        key=""
        autoreconnect="false"
        retain="false"
        cert=""
        persistOnError = "false"
      [Writable.Pipeline.Functions.MQTTSend.Addressable]
        Address=   "localhost"
        Port=      1883
        Protocol=  "tcp"
        Publisher= "MyApp"
        User=      ""
        Password=  ""
        Topic=     "sampleTopic"

[Service]
BootTimeout = "30s"
ClientMonitor = "15s"
CheckInterval = "10s"
Host = "localhost"
Port = 48095
Protocol = "http"
ReadMaxLimit = 100
StartupMsg = "Sample Configurable Application Service Started"
Timeout = "5s"

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

# Database is require when Store and Forward is enabled
[Database]
Type = "mongodb"
Host = "localhost"
Port = 27017
Timeout = "30s"
Username = ""
Password = ""

# SecretStore is required when Store and Forward is enabled and running with security
# so Databse credentails can be pulled from Vault.
[SecretStore]
  Host = 'localhost'
  Port = 8200
  Path = '/v1/secret/edgex/application-service/'
  Protocol = 'https'

  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'
  AuthToken = 'edgex'

[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "localhost"
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic="example"

[MessageBus]
Type = "zero"
    [MessageBus.SubscribeHost]
        Host = "localhost"
        Port = 5563
        Protocol = "tcp"
    [MessageBus.PublishHost]
        Host = "*"
        Port = 5565
        Protocol = "tcp"

[Logging]
EnableRemote = false
File = "./logs/app-service-configurable.log"
