[Writable]
  LogLevel = "INFO"

  [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = "5m"
    MaxRetryCount = 10

  [Writable.Pipeline]
    ExecutionOrder = "TransformToJSON, MQTTSend, MarkAsPushed"

    [Writable.Pipeline.Functions.TransformToJSON]
    [Writable.Pipeline.Functions.MarkAsPushed]
    [Writable.Pipeline.Functions.FilterByDeviceName]
      [Writable.Pipeline.Functions.FilterByDeviceName.Parameters]
        DeviceNames = ""
    [Writable.Pipeline.Functions.FilterByValueDescriptor]
      [Writable.Pipeline.Functions.FilterByValueDescriptor.Parameters]
        ValueDescriptors = ""
    [Writable.Pipeline.Functions.MQTTSend]
      [Writable.Pipeline.Functions.MQTTSend.Parameters]
        qos="0"
        key=""
        autoreconnect="false"
        retain="false"
        cert=""
        persistOnError = "false"
      [Writable.Pipeline.Functions.MQTTSend.Addressable]
        Address=   "localhost"
        Port=      1883
        Protocol=  "tcp"
        Publisher= "AppServiceConfigurable-mqtt-export"
        User=      ""
        Password=  ""
        Topic=     "edgex-events"

[Service]
BootTimeout = "30s"
ClientMonitor = "15s"
CheckInterval = "10s"
Host = "localhost"
Port = 50002
Protocol = "http"
ReadMaxLimit = 100
StartupMsg = "AppServiceConfigurable-mqtt-export has Started"
Timeout = "5s"

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

# Database is require when Store and Forward is enabled
# Note when running in docker from compose file set the following environment variables:
# - Databse_Host: edgex-mongo
[Database]
Type = "mongodb"
Host = "localhost"
Port = 27017
Timeout = "30s"
Username = ""
Password = ""

# SecretStore is required when Store and Forward is enabled and running with security
# so Databse credentails can be pulled from Vault.
# Note when running in docker from compose file set the following environment variables:
#   - SecretStore_Host: edgex-vault
#   - SecretStore_ServerName: edgex-vault
#   - SecretStore_RootCaCertPath: /vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem
#   - SecretStore_TokenFile: /vault/config/assets/resp-init.json
[SecretStore]
  Host = 'localhost'
  Port = 8200
  Path = '/v1/secret/edgex/appservice/'
  Protocol = 'https'

  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'
  AuthToken = 'edgex'

[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "localhost"
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Binding]
Type="messagebus"
SubscribeTopic="events"

[MessageBus]
Type = "zero"
    [MessageBus.SubscribeHost]
        Host = "localhost"
        Port = 5563
        Protocol = "tcp"

[Logging]
EnableRemote = false
File = "./logs/app-service-configurable-mqtt-export.log"
